# Generated by Django 3.1.6 on 2021-02-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onedssuperstore',
            fields=[
                ('Row_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Order_ID', models.CharField(max_length=100)),
                ('Order_Date', models.DateField()),
                ('Ship_Date', models.DateField()),
                ('Ship_Mode', models.CharField(max_length=100)),
                ('Customer_ID', models.CharField(max_length=100)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Segment', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Postal_Code', models.BigIntegerField()),
                ('Region', models.CharField(max_length=100)),
                ('Product_ID', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Sub_Category', models.CharField(max_length=100)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Sales', models.DecimalField(decimal_places=5, max_digits=15)),
                ('Quantity', models.BigIntegerField()),
                ('Discount', models.DecimalField(decimal_places=5, max_digits=15)),
                ('Profit', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
        ),
    ]
